### ISSUE TITLE
capv-controller-manager pod is in a crash loop

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#1155]
/kind bug

**What steps did you take and what happened:**
1. Create workload cluster with two devices
2. After workload cluster is deployed successfully, delete a device from VC
3. Step2 caused capv-controller-manager pod crash

```
goroutine 421 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1f37b60, 0xc0007f9380)
    /usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-vsphere/pkg/util.GetMachineMetadata(0xc000629be0, 0x19, 0x1ab7815, 0x9, 0xc000826120, 0x28, 0xc000629be0, 0x19, 0x0, 0x0, ...)
    /workspace/pkg/util/machines.go:147 +0x8b9
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).reconcileMetadata(0x3567598, 0xc000e4e180, 0x0, 0x0, 0xe)
    /workspace/pkg/services/govmomi/service.go:227 +0x102
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).ReconcileVM(0x3567598, 0xc0008321e0, 0x20bf000, 0x29, 0xc00089cd00, 0x0, 0x0, 0xc000b67828, 0x1443a0e, 0xc0006d3110, ...)
    /workspace/pkg/services/govmomi/service.go:125 +0xa77
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.reconcileNormal(0xc000707a80, 0xc0008321e0, 0xc0001f3b80, 0xc0006d3100, 0xc000629be0, 0x19)
    /workspace/controllers/vspherevm_controller.go:326 +0x22f
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.Reconcile(0xc000707a80, 0xc00058cfb0, 0x6, 0xc000629be0, 0x19, 0xc000912f00, 0x0, 0x0, 0x0)
    /workspace/controllers/vspherevm_controller.go:280 +0x783
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00013c630, 0x1de7780, 0xc00092d1a0, 0x354ec00)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:255 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00013c630, 0xc00056a900)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:231 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00013c630)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:210 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000928050)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000928050, 0x3b9aca00, 0x0, 0x1, 0xc00009a0c0)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000928050, 0x3b9aca00, 0xc00009a0c0)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:192 +0x468
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
I understand the cause of the controller-manager failure here. I need direction around what should happen to the cluster/machine when a network device that it expects to be there is missing?

**Comment by srm09** [comment]
Created the above PR with a possible resolution, we could discuss more around what could be the corrective action we could take here if any.
