### ISSUE TITLE
Capv crash after deleting vsphere deployment zones

### ISSUE THREAD

**Issue by mwright-pivotal** [kubernetes-sigs/cluster-api-provider-vsphere#1532]
/kind bug

Trying to delete vsphere deployment zones....

```
I0511 16:28:55.175241       1 vspheredeploymentzone_controller.go:262] capv-controller-manager/vspheredeploymentzone-controller "msg"="Deleting VSphereDeploymentZone"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1bb2233]

goroutine 558 [running]:
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vsphereDeploymentZoneReconciler.reconcileDelete.func1(0xc00040bc40, 0xc000543b01)
	/workspace/controllers/vspheredeploymentzone_controller.go:271 +0x33
sigs.k8s.io/cluster-api/util/collections.And.func1(0xc00040bc40, 0xb)
	/go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.0/util/collections/machine_filters.go:38 +0x65
sigs.k8s.io/cluster-api/util/collections.newFilteredMachineCollection(0xc000bd6840, 0xc00049c6c0, 0xb, 0xb, 0xc00040c301)
	/go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.0/util/collections/machine_collection.go:136 +0x8c
sigs.k8s.io/cluster-api/util/collections.Machines.Filter(0xc00036ca80, 0xc000bd1750, 0x2, 0x2, 0xc0001875e0)
	/go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.0/util/collections/machine_collection.go:145 +0x65
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vsphereDeploymentZoneReconciler.reconcileDelete(0xc000244540, 0xc000bc6d80, 0x25b2f48, 0xc000854b40, 0xc000187500, 0x0)
	/workspace/controllers/vspheredeploymentzone_controller.go:270 +0x1ab
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vsphereDeploymentZoneReconciler.Reconcile(0xc000244540, 0x259d518, 0xc000cefe90, 0x0, 0x0, 0xc0008579c0, 0xa, 0xc000cefe00, 0x0, 0x0, ...)
	/workspace/controllers/vspheredeploymentzone_controller.go:148 +0x80d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000281220, 0x259d518, 0xc000cefe60, 0x0, 0x0, 0xc0008579c0, 0xa, 0xc000cefe00, 0x0, 0x0, ...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000281220, 0x259d470, 0xc0008c2140, 0x1fd6d20, 0xc000ced5c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000281220, 0x259d470, 0xc0008c2140, 0x442300)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0007b03c0, 0xc000281220, 0x259d470, 0xc0008c2140)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x425
mwright@cumulus:~/projects/edge-h
```

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Similar to #1424 fixed by #1426
/close
Thanks for raising this, using the version 1.1.0 and above should not cause this issue.
