### ISSUE TITLE
Run e2e locally failed due to mismatch ginkgo version

### ISSUE THREAD

**Issue by zhanggbj** [kubernetes-sigs/cluster-api-provider-vsphere#1842]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Run e2e locally with `make e2e`

**What did you expect to happen:**
Run e2e successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It failed with error message below. It looks like the ginkgo package in go.mod is **2.9.1** but ginkgo package in hack/tools is **2.8.3** 

```
Contents of /Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/hack/tools/bin:
ginkgo		govc		kind		kustomize

time /Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/hack/tools/bin/ginkgo -v -focus="multivc"  -timeout=2h \
		--output-dir="/Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/_artifacts" --junit-report="junit.e2e_suite.1.xml" ./test/e2e -- \
		--e2e.config=""/Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/test/e2e/config/vsphere-dev.yaml"" \
		--e2e.artifacts-folder="/Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/_artifacts" \
		--e2e.skip-resource-cleanup=true \
		--e2e.use-existing-cluster="false"
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
  Ginkgo CLI Version:
    2.8.3
  Mismatched package versions found:
    2.9.1 used by e2e

  Ginkgo will continue to attempt to run but you may see errors (including flag
  parsing errors) and should either update your go.mod or your version of the
  Ginkgo CLI to match.

  To install the matching version of the CLI run
    go install github.com/onsi/ginkgo/v2/ginkgo
  from a path that contains a go.mod file.  Alternatively you can use
    go run github.com/onsi/ginkgo/v2/ginkgo
  from a path that contains a go.mod file to invoke the matching version of the
  Ginkgo CLI.

  If you are attempting to test multiple packages that each have a different
  version of the Ginkgo library with a single Ginkgo CLI that is currently
  unsupported.

/Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/test/e2e/e2e.test flag redefined: ginkgo.seed
panic: /Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/test/e2e/e2e.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000a4180, {0x3b6cb38, 0x5373c80}, {0xc0006128e0, 0xb}, {0x37cf872, 0x2a})
	/usr/local/go/src/flag/flag.go:982 +0x2f9
flag.(*FlagSet).Int64Var(...)
	/usr/local/go/src/flag/flag.go:769
github.com/onsi/ginkgo/config.Flags(0x3755601?, {0x37537d0?, 0x2e2b02f?}, 0x1)
	/Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/vendor/github.com/onsi/ginkgo/config/config.go:75 +0xf1
github.com/onsi/ginkgo.init.0()
	/Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:53 +0x35
Could not open /Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/_artifacts/test_e2e_junit.e2e_suite.1.xml:
open /Users/gongz/zhangg/workspace/src/sigs.k8s.io/cluster-api-provider-vsphere/_artifacts/test_e2e_junit.e2e_suite.1.xml: no such file or directory

Ginkgo ran 1 suite in 8.931088875s

Test Suite Failed

real	0m9.601s
user	0m6.748s
sys	0m4.294s
make: *** [e2e] Error 1
```

**Environment:**

- Cluster-api-provider-vsphere version:  main branch
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
```
- OS (e.g. from `/etc/os-release`): macos

**Comment by zhanggbj** [comment]
This is fixed, close it!
