### ISSUE TITLE
reconcileUUID has issue. null pointer  

### ISSUE THREAD

**Issue by spyroot** [kubernetes-sigs/cluster-api-provider-vsphere#953]
Below is a log, I check VM has UUID attached to it.  I'm not 100% positive it on the cluster API side. I open a bug in govmomi as well.  I 've checked it looks like 

VirtualMachine.UUID on handle all null pointer checks.

2020-07-05T03:35:21.216104377Z stderr F I0705 03:35:21.215663       1 vspheremachine_controller.go:345] capv-controller-manager/vspheremachine-controller/default/dev-
cnfs-control-plane-2vs8p "msg"="provider ID is not reconciled"
2020-07-05T03:35:21.216125249Z stderr F I0705 03:35:21.215854       1 controller.go:282] controller-runtime/controller "msg"="Successfully Reconciled"  "controller"="
vspheremachine" "request"={"Namespace":"default","Name":"dev-cnfs-control-plane-2vs8p"}
2020-07-05T03:35:21.321600047Z stderr F I0705 03:35:21.320843       1 util.go:81] capv-controller-manager/vspherevm-controller/default/dev-cnfs-control-plane-8k97s "m
sg"="using inventory path to find vm"  "path"="/RegionA01/vm/k8s/dev-cnfs-control-plane-8k97s"
2020-07-05T03:35:21.379459183Z stderr F I0705 03:35:21.378864       1 util.go:89] capv-controller-manager/vspherevm-controller/default/dev-cnfs-control-plane-8k97s "m
sg"="vm found by name"  "vmref"={"Type":"VirtualMachine","Value":"vm-469"}
2020-07-05T03:35:21.392021621Z stderr F I0705 03:35:21.391189       1 vspherevm_controller.go:229] capv-controller-manager/vspherevm-controller/default/dev-cnfs-contr
ol-plane-8k97s "msg"="resource is patched"  "local-resource-version"="923384" "remote-resource-version"="923385"
2020-07-05T03:35:21.405696389Z stderr F E0705 03:35:21.404812       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime er
ror: invalid memory address or nil pointer dereference)
2020-07-05T03:35:21.405817843Z stderr F goroutine 361 [running]:
2020-07-05T03:35:21.405838755Z stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1bfa2a0, 0x331b230)
2020-07-05T03:35:21.405852393Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:74 +0xa3
2020-07-05T03:35:21.405865289Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2020-07-05T03:35:21.405878822Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:48 +0x82
2020-07-05T03:35:21.405892124Z stderr F panic(0x1bfa2a0, 0x331b230)
2020-07-05T03:35:21.405905957Z stderr F         /usr/local/go/src/runtime/panic.go:679 +0x1b2
2020-07-05T03:35:21.405929687Z stderr F github.com/vmware/govmomi/object.VirtualMachine.UUID(0x0, 0x0, 0xc0002f02c0, 0xc000b60600, 0xe, 0xc000b60620, 0x6, 0x228e5a0,
0xc000b58480, 0x10, ...)
2020-07-05T03:35:21.405966602Z stderr F         /go/pkg/mod/github.com/vmware/govmomi@v0.23.0/object/virtual_machine.go:859 +0x1f7
2020-07-05T03:35:21.405995032Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).reconcileUUID(...)
2020-07-05T03:35:21.406014247Z stderr F         /workspace/pkg/services/govmomi/service.go:263
2020-07-05T03:35:21.406029576Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).ReconcileVM(0x336ff10, 0xc000823860, 0x1fa7320, 0x2
9, 0x8, 0x2260da0, 0xc000bc2600, 0x0, 0x0, 0xc000bc2600, ...)
2020-07-05T03:35:21.406043651Z stderr F         /workspace/pkg/services/govmomi/service.go:107 +0x7fb
2020-07-05T03:35:21.406058215Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.reconcileNormal(0xc0004bfe40, 0xc000823860, 0xc000379400, 0x
c0006ad000, 0xc00084de20, 0x1c)
2020-07-05T03:35:21.406073261Z stderr F         /workspace/controllers/vspherevm_controller.go:311 +0x20c
2020-07-05T03:35:21.406126979Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.Reconcile(0xc0004bfe40, 0xc000e32ef9, 0x7, 0xc000e31e40, 0x1
c, 0xc000c1dc00, 0x0, 0x0, 0x0)
2020-07-05T03:35:21.406145807Z stderr F         /workspace/controllers/vspherevm_controller.go:272 +0x76b
2020-07-05T03:35:21.406167572Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00014acc0, 0x1cee160, 0xc000b25300, 0
x0)
2020-07-05T03:35:21.406185846Z stderr F         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256 +0x162
2020-07-05T03:35:21.406199628Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00014acc0, 0xc000279900)
2020-07-05T03:35:21.406212777Z stderr F         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232 +0xcb
2020-07-05T03:35:21.406225629Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00014acc0)
2020-07-05T03:35:21.406237442Z stderr F         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211 +0x2b
2020-07-05T03:35:21.40624954Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0002270e0)
2020-07-05T03:35:21.406269273Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x5e
2020-07-05T03:35:21.406435007Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002270e0, 0x3b9aca00, 0x0, 0xc000473701, 0xc0003081e0)
2020-07-05T03:35:21.406460006Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8
2020-07-05T03:35:21.406476104Z stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc0002270e0, 0x3b9aca00, 0xc0003081e0)
2020-07-05T03:35:21.406490569Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x4d
2020-07-05T03:35:21.406513294Z stderr F created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
2020-07-05T03:35:21.406529336Z stderr F         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:193 +0x328
2020-07-05T03:35:21.415359659Z stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2020-07-05T03:35:21.41546341Z stderr F  panic: runtime error: invalid memory address or nil pointer dereference
2020-07-05T03:35:21.415483845Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x18f1357]
2020-07-05T03:35:21.415493888Z stderr F
2020-07-05T03:35:21.415507469Z stderr F goroutine 361 [running]:
2020-07-05T03:35:21.415521471Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2020-07-05T03:35:21.415534738Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:55 +0x105
2020-07-05T03:35:21.416116492Z stderr F panic(0x1bfa2a0, 0x331b230)
2020-07-05T03:35:21.416173805Z stderr F         /usr/local/go/src/runtime/panic.go:679 +0x1b2
2020-07-05T03:35:21.416198315Z stderr F github.com/vmware/govmomi/object.VirtualMachine.UUID(0x0, 0x0, 0xc0002f02c0, 0xc000b60600, 0xe, 0xc000b60620, 0x6, 0x228e5a0,
0xc000b58480, 0x10, ...)
2020-07-05T03:35:21.416215481Z stderr F         /go/pkg/mod/github.com/vmware/govmomi@v0.23.0/object/virtual_machine.go:859 +0x1f7
2020-07-05T03:35:21.416229724Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).reconcileUUID(...)
2020-07-05T03:35:21.416243049Z stderr F         /workspace/pkg/services/govmomi/service.go:263
2020-07-05T03:35:21.416254857Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).ReconcileVM(0x336ff10, 0xc000823860, 0x1fa7320, 0x2
9, 0x8, 0x2260da0, 0xc000bc2600, 0x0, 0x0, 0xc000bc2600, ...)
2020-07-05T03:35:21.416268939Z stderr F         /workspace/pkg/services/govmomi/service.go:107 +0x7fb
2020-07-05T03:35:21.416281812Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.reconcileNormal(0xc0004bfe40, 0xc000823860, 0xc000379400, 0x
c0006ad000, 0xc00084de20, 0x1c)
2020-07-05T03:35:21.416296556Z stderr F         /workspace/controllers/vspherevm_controller.go:311 +0x20c
2020-07-05T03:35:21.416315085Z stderr F sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.Reconcile(0xc0004bfe40, 0xc000e32ef9, 0x7, 0xc000e31e40, 0x1
c, 0xc000c1dc00, 0x0, 0x0, 0x0)
2020-07-05T03:35:21.416331951Z stderr F         /workspace/controllers/vspherevm_controller.go:272 +0x76b
2020-07-05T03:35:21.416345377Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00014acc0, 0x1cee160, 0xc000b25300, 0
x0)
2020-07-05T03:35:21.41635826Z stderr F  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256 +0x162
2020-07-05T03:35:21.416614236Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00014acc0, 0xc000279900)
2020-07-05T03:35:21.416757723Z stderr F         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232 +0xcb
2020-07-05T03:35:21.41737585Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00014acc0)
2020-07-05T03:35:21.417690338Z stderr F         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211 +0x2b
2020-07-05T03:35:21.417997498Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0002270e0)
2020-07-05T03:35:21.418018308Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x5e
2020-07-05T03:35:21.424262593Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002270e0, 0x3b9aca00, 0x0, 0xc000473701, 0xc0003081e0)
2020-07-05T03:35:21.424861195Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8
2020-07-05T03:35:21.425741417Z stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc0002270e0, 0x3b9aca00, 0xc0003081e0)
2020-07-05T03:35:21.42611014Z stderr F  /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x4d
2020-07-05T03:35:21.426608704Z stderr F created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
2020-07-05T03:35:21.426917582Z stderr F         /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:193 +0x328

Environment:
vSphere 6.7.

Cluster-api-provider-sphere version:
I use TKG 1.1.2.

Kubernetes version: (use kubectl version):
1.18.3+vmware

OS (e.g. from /etc/os-release):

**Comment by yastij** [comment]
@spyroot - the fix was merged on the govmomi side https://github.com/vmware/govmomi/pull/2044 and picked up in CAPV https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/948, closing

**Comment by spyroot** [comment]
Thank you !
